services:
    bite_codes_rest_api_generator.serialization_subscriber:
        class: BiteCodes\RestApiGeneratorBundle\Subscriber\SerializationSubscriber
        arguments:
            - '@jms_serializer'
            - '@bite_codes_rest_api_generator.services.response_data'
            - '@bite_codes.rest_api_generator.endpoint_manager'
        tags:
            - { name: kernel.event_subscriber }

    bite_codes_rest_api_generator.json_content_subscriber:
        class: BiteCodes\RestApiGeneratorBundle\Subscriber\JsonContentSubscriber
        tags:
            - { name: kernel.event_subscriber }

    bite_codes_rest_api_generator.subscriber.api_exception_subscriber:
        class: BiteCodes\RestApiGeneratorBundle\Subscriber\ApiExceptionSubscriber
        arguments:
            - '%kernel.debug%'
        tags:
            - { name: kernel.event_subscriber }

    bite_codes_rest_api_generator.subscriber.nested_resource_subscriber:
        class: BiteCodes\RestApiGeneratorBundle\Subscriber\NestedResourceSubscriber
        arguments:
            - '@bite_codes.rest_api_generator.endpoint_manager'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    bite_codes_rest_api_generator.subscriber.entity_resolver_subscriber:
        class: BiteCodes\RestApiGeneratorBundle\Subscriber\EntityResolverSubscriber
        tags:
            - { name: kernel.event_subscriber }

    app.routing_loader:
        class: BiteCodes\RestApiGeneratorBundle\RouteLoader\RouteLoader
        arguments:
            - '@bite_codes.rest_api_generator.endpoint_manager'
        tags:
            - { name: routing.loader }

    bite_codes_rest_api_generator.form.dynamic_form_type:
        class: BiteCodes\RestApiGeneratorBundle\Form\DynamicFormType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: dynamic_form_type }

    bite_codes_rest_api_generator.form.batch_create_type:
            class: BiteCodes\RestApiGeneratorBundle\Form\BatchCreateType
            tags:
                - { name: form.type, alias: batch_create_type }

    bite_codes_rest_api_generator.annotation.generate_api_doc_handler:
        class: BiteCodes\RestApiGeneratorBundle\Annotation\GenerateApiDocHandler
        arguments:
            - '@bite_codes.rest_api_generator.endpoint_manager'
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@service_container'
        tags:
            - { name: nelmio_api_doc.extractor.handler }

    bite_codes_rest_api_generator.services.response_data:
        class: BiteCodes\RestApiGeneratorBundle\Services\MetadataStorage\ResponseData