language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.5
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - composer self-update
  - mkdir -p build/logs
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

matrix:
    allow_failures:
        - php: hhvm

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

after_script:
  - travis_retry php vendor/bin/coveralls -v
