language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - mkdir -p build/logs

matrix:
    allow_failures:
        - php: hhvm

install: composer update --prefer-dist

after_script:
  - travis_retry php vendor/bin/coveralls -v
