language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.8.*

before_install:
  - wget http://getcomposer.org/composer.phar
  - mkdir -p build/logs
  - if [ "$SYMFONY_VERSION" != "" ]; then php composer.phar require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION=3.0.*
    - php: 5.5
      env: SYMFONY_VERSION=3.1.*
    - php: 5.5
      env: SYMFONY_VERSION=3.2.*
    - php: 5.5
      env: SYMFONY_VERSION=3.3.*
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"

install:
  - php -d memory_limit=-1 composer.phar update --prefer-dist $COMPOSER_FLAGS

after_script:
  - travis_retry php vendor/bin/coveralls -v
