language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"

before_install:
  - composer self-update
  - mkdir -p build/logs

matrix:
    allow_failures:
        - php: hhvm

install:
  - composer update --prefer-dist
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

after_script:
  - travis_retry php vendor/bin/coveralls -v
